### ISSUE TITLE
Tomcat hangs w/Null Point Exception during reload

### ISSUE THREAD

**Issue by gskaplan** [skyscreamer/nevado#52]
Application contains several listeners that connect at start-up. Within Eclipse, during the development cycle (code change, re-publish, etc.), frequently Tomcat will be unable to shut-down and must be killed via the Windows Task Manager. The following stack trace is also displayed in the console prior to killing Tomcat (Spring configuration follows the stack trace):

java.lang.NullPointerException
       at org.skyscreamer.nevado.jms.connector.AbstractSQSConnector.receiveSQSMessage(AbstractSQSConnector.java:168)
       at org.skyscreamer.nevado.jms.connector.AbstractSQSConnector.receiveMessage(AbstractSQSConnector.java:95)
       at org.skyscreamer.nevado.jms.NevadoSession.getUnfilteredMessage(NevadoSession.java:462)
       at org.skyscreamer.nevado.jms.NevadoSession.receiveMessage(NevadoSession.java:425)
       at org.skyscreamer.nevado.jms.NevadoMessageConsumer.processAsyncMessage(NevadoMessageConsumer.java:133)
       at org.skyscreamer.nevado.jms.AsyncConsumerRunner.processMessage(AsyncConsumerRunner.java:76)
       at org.skyscreamer.nevado.jms.AsyncConsumerRunner.run(AsyncConsumerRunner.java:37)
       at java.lang.Thread.run(Thread.java:722)

=== SPRING CONFIGURATION ===============

```
<bean id="sqsConnectorFactory" class="org.skyscreamer.nevado.jms.connector.amazonaws.AmazonAwsSQSConnectorFactory" />

<bean id="connectionFactory" class="org.skyscreamer.nevado.jms.NevadoConnectionFactory">
    <property name="sqsConnectorFactory" ref="sqsConnectorFactory" />
    <property name="awsAccessKey" value="${aws.publicKey}" />
    <property name="awsSecretKey" value="${aws.secretKey}" />
</bean>   

<bean id="jmsTemplate" class="org.springframework.jms.core.JmsTemplate">
    <property name="pubSubDomain" value="true"/>
    <property name="defaultDestinationName" value="UserEvents#{T(com.kaplansoftware.util.StageUtils).getResourceSuffixForCurrentStage()}"/>
    <property name="connectionFactory" ref="connectionFactory"/>
</bean>

<bean id="userEventTopic" class="org.skyscreamer.nevado.jms.destination.NevadoTopic">
    <constructor-arg value="UserEvents#{T(com.kaplansoftware.util.StageUtils).getResourceSuffixForCurrentStage()}" />
</bean>

<!-- Event Listeners -->

<bean id="emailEventListener" class="com.kaplansoftware.crm.EmailUserEventListener" />
<bean id="emailContainer" class="org.springframework.jms.listener.SimpleMessageListenerContainer">
    <property name="connectionFactory" ref="connectionFactory"/>
    <property name="messageListener">
        <bean id="auditListener" class="org.springframework.jms.listener.adapter.MessageListenerAdapter">
            <property name="delegate" ref="emailEventListener"/>
            <property name="defaultResponseDestination" ref="userEventTopic"/>
        </bean>
    </property>
    <property name="destination" ref="userEventTopic"/>
</bean>


<bean id="auditEventListener" class="com.kaplansoftware.audit.AuditManager" />
<bean id="auditContainer" class="org.springframework.jms.listener.SimpleMessageListenerContainer">
    <property name="connectionFactory" ref="connectionFactory"/>
    <property name="messageListener">
        <bean id="auditListener" class="org.springframework.jms.listener.adapter.MessageListenerAdapter">
            <property name="delegate" ref="auditEventListener"/>
            <property name="defaultResponseDestination" ref="userEventTopic"/>
        </bean>
    </property>
    <property name="destination" ref="userEventTopic"/>
</bean>


<bean id="mailchimpEventListener" class="com.kaplansoftware.crm.mailchimp.MailChimpUserEventListener" />
<bean id="mailchimpListener" class="org.springframework.jms.listener.adapter.MessageListenerAdapter">
    <property name="delegate" ref="mailchimpEventListener"/>
    <property name="defaultResponseDestination" ref="userEventTopic"/>
</bean>
<bean id="mailchimpContainer" class="org.springframework.jms.listener.SimpleMessageListenerContainer">
    <property name="connectionFactory" ref="connectionFactory"/>
    <property name="messageListener" ref="mailchimpListener"/>
    <property name="destination" ref="userEventTopic"/>
</bean>
```

**Comment by carterpage** [comment]
Looks like we need to change

```
if (!connection.isRunning()) {
```

to

```
if (message != null && !connection.isRunning()) {
```

in AbstractSQSConnector.

I will try to add a unit test for this too.

**Comment by carterpage** [comment]
@gskaplan Can you confirm this is fixed in 1.2.2?

**Comment by gskaplan** [comment]
I did not try it yet, as last week I had been waiting for it to show up in Maven (which it still isn’t). The holiday weekend then got in the way for any testing. I will try and download the jar later tonight and test.

Thanks,
Gerry

n  I’m shocked how long it’s taking for it to show up in Maven.

**Comment by carterpage** [comment]
I'm surprised too!  I wonder if something broke down in the maven network.
 If it doesn't pop up in a couple of days, I'll ping the guys at Sonatype.

In the meantime, you can download the jar here:

http://search.maven.org/remotecontent?filepath=org/skyscreamer/nevado-jms/1.2.2/nevado-jms-1.2.2.jar

and the pom here:

http://search.maven.org/remotecontent?filepath=org/skyscreamer/nevado-jms/1.2.2/nevado-jms-1.2.2.pom

and install it into your local repo with mvn install:install-file:

http://maven.apache.org/plugins/maven-install-plugin/usage.html

This shoudl do the trick:

```
mvn install:install-file -Dfile=nevado-jms-1.2.2.jar
```

-DpomFile=nevado-jms-1.2.2.pom

**Comment by gskaplan** [comment]
OK, I installed it into my local maven – thanks for the mvn command. I’ve got it up and running in my test environment so I will make some bogus source code changes that will cause republishing and see if it hangs at all. I’ll let you know what I find.

Thanks,
Gerry

**Comment by carterpage** [comment]
Fixed in #53
